config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:index, :show]

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index'
    end

    unauthenticated :user do
      root 'devise/sessions#new'
    end
  end

  resources :posts do
    member do
      post "like", to: "posts#upvote", as: "like"
      post "dislike", to: "posts#downvote", as: "dislike"
    end
  end


  post 'comments' => 'comments#create', as: "create_comment"

  resources :users do
    member do
      put "add", to: "friendship#add", as: "add"
      put "accept", to: "friendship#accept", as: "accept"
      put "decline", to: "friendship#decline", as: "decline"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  

  belongs_to :user

  mount_uploader :attachment, AvatarUploader

  acts_as_votable

  acts_as_commentable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_friendship

  mount_uploader :avatar, AvatarUploader

  has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password_confirmation, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])

    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!


  def create
    post = Post.find_by(id: params[:id])
    comment = post.comments.build(comment_params)
    comment.user = current_user

    if comment.save
      flash[:notice] = "Comment has been created."
      redirect_to :back
    else
      flash[:alert] = "Comment has not been created."
    end

  end

  private
  def comment_params
      params.permit(:comment)
  end
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController

  def add

    @user = User.find(params[:id])

    current_user.friend_request(@user)

    redirect_to :back
  end

  def accept

    @user = User.find(params[:id])
    current_user.accept_request(@user)
    redirect_to :back

  end

  def decline

    @user = User.find(params[:id])
    current_user.decline_request(@user)
    redirect_to :back

  end

  def remove

    @user = User.find(params[:id])
    current_user.remove_friend(@user)

  end

  def block

    @user = User.find(params[:id])
    current_user.block_friend(@user)

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front
  end

  def index
    @post = Post.new
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :find_likeable
 before_action :authenticate_user!
 respond_to :js

 def create
   @likeable.liked_by current_user
 end

 def destroy
   @likeable.disliked_by current_user
 end

 private
 def find_likeable
   @likeable_type = params[:likeable_type].classify
   @likeable = @likeable_type.constantize.find(params[:likeable_id])
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @friends = current_user.friends

    @post = Post.new

    @posts = Array.new

    current_user.posts.each do |post|
       @posts<<post
    end

    @friends.each do |friend|
        friend.posts.each do |post|
            @posts<<post
        end
    end

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts

  def create
    @post = Post.new(post_params) do |post|
      post.user = current_user
    end
    if @post.save
      redirect_to root_path
    else
      redirect_to root_path, notice: @post.errors.full_messages.first
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to :back
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to posts_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to posts_path
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:comment, :attachment, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @friends = @user.friends
    @added = false
    @alreadyFriends = false
    @friendRequests = current_user.requested_friends
    @pendings = current_user.pending_friends
    @pendings.each do |pend|
        if pend== @user
            @added = true
        end
    end
    @friends.each do |friend|
        if current_user== friend
            @alreadyFriends = true
        end
    end


    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @user = User.find(params[:id])
  end


  def update

    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path

  end

private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :avatar_cache, :id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <div class="info">
    <%= render 'shared/avatar', user: comment.user %>
    <h4 class="name"><%= link_to comment.user.name, user_path(comment.user) %></h4>
  </div>
  <div class="content">
    <div class="row">
      <span class="text"><%= comment.comment_html %></span>
    </div>
    <div class="pull-right">
      <% if belongs_to_user?(comment) %>
        <%= link_to comment_path(comment), method: :delete, class: 'btn btn-danger btn-sm', remote: true do %>
          <% fa_icon 'trash' %>
        <% end %>
      <% end %>
    </div>
  </div>
  <br>
  <hr>
</div>

app/views/comments/_form.html.erb
<div id="mentionable-data" data-content="<%= mentionable_user_path(current_user) %>"></div>
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), id: 'new_comment', method: :post, remote: true do %>
  <div class="form-group">
    <div id="comment-text" contenteditable="true" class="editable form-control input-mentionable" placeholder="Enter Comment"></div>
    <%= hidden_field_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control input-mentionable' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$("#<%= @commentable_type.downcase %>-<%= @commentable.id %> .comments").prepend("<%=j render(@comment) %>");
$("#comment_text").val("");

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacePump</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container-fluid">
    <nav class="navbar navbar-inverse">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-4">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"> <strong>FACEPUMP</strong></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-4">
              <% if user_signed_in? %>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Newsfeed", posts_path, :class => 'navbar-link'  %></li>
                <li><%= link_to 'My profile', user_path(current_user), :class => 'navbar-link' %>
                <li>  <%= link_to 'Search friends', users_path, :class => 'navbar-link' %>
                </li>
                <li><%= link_to 'Edit profile', edit_user_path(current_user), :class => 'navbar-link' %> </li>
                <li><%= link_to 'Account settings', edit_user_registration_path, :class => 'navbar-link' %> </li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link'  %></li>
                <li>
                  <strong class ="navbar-link ">
                  <%if current_user.avatar.url.present? %>
                    <%= image_tag(current_user.avatar.url, height: '64', width: '64') %>
                  <%end%>
                </li>
              </ul>
              <% else %>
                <ul class="nav navbar-nav navbar-right">
                  <li>  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
                  <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
                </ul>
              <%end%>

            </div><!-- /.navbar-collapse -->
          </div><!-- /.container -->
        </nav><!-- /.navbar -->
        </div>

    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<% if current_user.liked? likeable %>
  <%= form_tag unlike_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), method: :post, remote: true do %>
    <% button_tag class: 'btn btn-block liked' do %>
      <%= fa_icon 'thumbs-up' %> unlike
    <% end %>
  <% end %>
<% else %>
  <%= form_tag like_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), remote: true do %>
    <% button_tag class: 'btn btn-block' do %>
      <%= fa_icon 'thumbs-up' %> like
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#<%= @likeable_type.downcase %>-<%= @likeable.id %> .like").html("<%=j render('likes/form', likeable: @likeable) %>");
$("#<%= @likeable_type.downcase %>-<%= @likeable.id %> .like-count").html("<%= pluralize(@likeable.cached_votes_up, 'like') %>");

app/views/likes/destroy.js.erb
$("#<%= @likeable_type.downcase %>-<%= @likeable.id %> .like").html("<%=j render('likes/form', likeable: @likeable) %>");
$("#<%= @likeable_type.downcase %>-<%= @likeable.id %> .like-count").html("<%= pluralize(@likeable.cached_votes_up, 'like') %>");

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="form-group">
   <h2>Create post</h2>
      <%= f.text_area :content, class: 'form-control', autofocus: true,
          placeholder: 'What\'s up?' %>
      <label for=":attachment">Upload image</label>
      <%= f.file_field :attachment, class: 'form-control' %>
  </div>
  <%= f.submit :post, class: 'btn btn-primary'%>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
 <div class="row">
	<div class="col-lg-6 col-lg-offset-4 well">
    <div class="row">
    </div>
    <h1>Newsfeed</h1>
    <%= form_for(@post) do |f| %>
      <div class="form-group">
       <h2>Create post</h2>
          <%= f.text_area :content, class: 'form-control', autofocus: true,
              placeholder: 'What\'s up?' %>
          <label for=":attachment">Upload image</label>
          <%= f.file_field :attachment, class: 'form-control' %>
      </div>
      <%= f.submit :post, class: 'btn btn-primary'%>
    <% end %>
    <h2>Posts lists</h2>
    <% @posts.each do |post| %>
		<div id="postlist">
        <div class="panel">
                <div class="panel-heading">
                    <div class="text-center">
                        <div class="row">
                          <div class="col-sm-3">
                              <h4 class="pull-left">
                              <small>
                                <% if post.user.avatar.url.present? %>
                                <%= image_tag(post.user.avatar.url, height: '64', width: '64') %>
                                <%end%>
                              </small>
                              </h4>
                          </div>
                          <div class="col-sm-9">
                                <h3 class="pull-left"><%= post.user.name %></h3>
                          </div>
                        </div>
                    </div>
                </div>

            <div class="panel-body">
                <a href="#" class="thumbnail">
                    <% if post.attachment.url.present? %>
                    <%= image_tag(post.attachment.url) %>
                    <%end%>
                </a>
                  <%=post.content %>
            </div>

            <div class="panel-footer">
                <span class="">

                  <%= button_to "Like", like_post_path(post), class: 'btn btn-primary' %>
                    <%= fa_icon 'thumbs-up' %>
                  <%= post.get_upvotes.size %>

                </span>
                <span class=" ">

                  <%= button_to "DisLike", dislike_post_path(post), class: 'btn btn-primary' %>
                    <%= fa_icon 'thumbs-down' %>
                   <%= post.get_downvotes.size %>

                </span>
                 <span class="label ">
                   <% if post.user == current_user %>
                   <%= link_to 'Edit', edit_post_path(post) %></td>
                   <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                   <% end %>
                 </span>
            </div>
        </div>
    </div>

    <div class="comment-section">

      <div class="container">
        <div class="row">
        <div class="col-sm-12">
        <h3>Comments</h3>
        </div><!-- /col-sm-12 -->
        </div><!-- /row -->

       <% @comments = post.comments.all %>
       <% @comments.each do |comment| %>
         <div class="row">
         <div class="col-sm-1">
         <div class="thumbnail">

         <% if comment.user.avatar.url.present? %>
           <%= image_tag(comment.user.avatar.url, height: '64', width: '64') %>
         <%end%>
         </div><!-- /thumbnail -->
         </div><!-- /col-sm-1 -->

         <div class="col-sm-5">
         <div class="panel panel-default">
         <div class="panel-heading">
         <strong><%=comment.user.name%></strong> <span class="text-muted"><%=comment.created_at%></span>
         </div>
         <div class="panel-body">
         <%= comment.comment %> <br>
         </div><!-- /panel-body -->
         </div><!-- /panel panel-default -->
         </div><!-- /col-sm-5 -->
         </div><!-- /row -->


       <% end %>
    </div>
    <div class="comment box">

      <div class="container">
        <div class="row">
          <h3>Add Comment</h3>
        </div>

        <div class="row">
          <div class="col-md-6">
               <div class="widget-area no-padding blank">
               <div class="status-upload">
                 <%= form_tag create_comment_path, method: "post" do %>
                 <%= hidden_field_tag "id", post.id %>
                 <%= text_area_tag :comment %>
                 <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> comment</button>
                 <% end %>
               </div><!-- Status Upload  -->
             </div><!-- Widget Area -->
           </div>
         </div>
       </div>
    </div>


<%end%>
</div>

</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attachment:</strong>
  <%= @post.attachment %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4 well">
    <h3 class="text-center">Edit Profile</h3>
    <br>
    <%= form_for(@user) do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', autofocus: true, placeholder: 'Full name' %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'email@example.com' %>
      </div>
      <label for="">Profile picture</label>
      <div class="field">

        <%= f.label :avatar do %>
          <%= f.file_field :avatar %>
          <%= f.hidden_field :avatar_cache %>
        <% end %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    <br>

  </div>
</div>

app/views/users/index.html.erb
<div class="row">
        <div class="col-xs-12 col-sm-offset-3 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading c-list">
                    <span class="title">Pumps</span>
                </div>
                <ul class="list-group" id="contact-list">
                  <% @users.each do |user| %>
                  <% if user!= current_user %>

                    <li class="list-group-item">
                        <div class="col-xs-12 col-sm-3">
                          <% if user.avatar.url.present? %>
                            <img src="<%= user.avatar.url %>" alt="Scott Stevens" class="img-responsive img-circle" />
                          <%end%>
                        </div>
                        <div class="col-xs-12 col-sm-9">
                            <span class="name"><a href="<%=user_path(user)%>"><%= user.name %></a></span><br/>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                    <%end%>
                    <% end %>
                </ul>
            </div>
        </div>
	</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>






<!--
User Profile Sidebar by @keenthemes
A component of Metronic Theme - #1 Selling Bootstrap 3 Admin Theme in Themeforest: http://j.mp/metronictheme
Licensed under MIT
-->

<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
          <% if @user.avatar.url.present? %>
            	<img src="<%=@user.avatar.url%>" class="img-responsive" alt="">
          <%end%>
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= @user.name %>
					</div>
					<div class="profile-usertitle-job">

					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">
            <%if @added == false &&  @user!= current_user  &&  @alreadyFriends == false %>
              <%= link_to 'Add friend', add_user_path(@user), method: :put %>
            <%end%>
            <% if @added == true %>
              <span>Friend Request sent</span>
            <%end%>
            <% if @user == current_user %>
              <span>Hello me </span>
            <%end%>
            <% if  @alreadyFriends %>
              <span>Already friend </span>
            <%end%>
          </button>

				</div>




				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
  							<i class="glyphicon glyphicon-user"></i>
  							Friend requests
              </a>
              <% if @user == current_user%>
                <ul class="list-group">
                  <% @friendRequests.each do |friend| %>
                    <li class="active">
          						<%=friend.name%>
                    </li>
                    <%= link_to 'Accept', accept_user_path(friend), method: :put %>
                    <%= link_to 'Decline', decline_user_path(friend), method: :put %>
                  <%end%>
                </ul>
              <%end%>
						</li>

            <li class="active">
							<a href="#">
  							<i class="glyphicon glyphicon-user"></i>
  							Friends list
              </a>

              <ul>
                <% @friends.each do |friend| %>
                  <li>

                    <% if friend.avatar.url.present? %>
                      <%= image_tag(friend.avatar.url, height: '34', width: '34') %>
                    <%end%>
                    <a href="<%=user_path(friend)%>"><%= friend.name %></a>
                  </li>
                <%end%>
              </ul>

						</li>

            <li class="active">
  							<%= link_to 'Search friends', users_path %>
						</li>
					</ul>
				</div>



				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">
              <% if @user == current_user%>
              <%= form_for(@post) do |f| %>
                <div class="form-group">
                 <h2>Create post</h2>
                    <%= f.text_area :content, class: 'form-control', autofocus: true,
                        placeholder: 'What\'s up?' %>
                    <label for=":attachment">Upload image</label>
                    <%= f.file_field :attachment, class: 'form-control' %>
                </div>
                <%= f.submit :post, class: 'btn btn-primary'%>
              <% end %>
              <% end %>

                <% @posts=@user.posts %>

                <h2>Posts lists</h2>
                <% @posts.reverse_each do |post| %>
                <div id="postlist">
                    <div class="panel">
                            <div class="panel-heading">
                                <div class="text-center">
                                    <div class="row">
                                      <div class="col-sm-3">
                                          <h4 class="pull-left">
                                          <small>
                                            <% if post.user.avatar.url.present? %>
                                            <%= image_tag(post.user.avatar.url, height: '64', width: '64') %>
                                            <%end%>
                                          </small>
                                          </h4>
                                      </div>
                                      <div class="col-sm-9">
                                            <h3 class="pull-left"><%= post.user.name %></h3>
                                      </div>
                                    </div>
                                </div>
                            </div>

                        <div class="panel-body">
                            <a href="#" class="thumbnail">
                                <% if post.attachment.url.present? %>
                                <%= image_tag(post.attachment.url) %>
                                <%end%>
                            </a>
                              <%=post.content %>
                        </div>

                        <div class="panel-footer">
                            <span class="label ">
                              <%= link_to like_post_path(post), method: :put do %>
                                <%= fa_icon 'thumbs-up' %>
                              <%= post.get_upvotes.size %>
                              <% end %>
                            </span>
                            <span class="label ">
                              <%= link_to dislike_post_path(post), method: :put do %>
                                <%= fa_icon 'thumbs-down' %>
                               <%= post.get_downvotes.size %>
                              <% end %>
                            </span>
                             <span class="label ">
                               <% if post.user == current_user %>
                               <%= link_to 'Edit', edit_post_path(post) %></td>
                               <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                               <% end %>
                             </span>
                        </div>
                    </div>
                </div>

                <div class="comment-section">

                  <div class="container">
                    <div class="row">
                    <div class="col-sm-12">
                    <h3>Comments</h3>
                    </div><!-- /col-sm-12 -->
                    </div><!-- /row -->

                   <% @comments = post.comments.all %>
                   <% @comments.each do |comment| %>
                     <div class="row">
                     <div class="col-sm-1">
                     <div class="thumbnail">

                     <% if comment.user.avatar.url.present? %>
                       <%= image_tag(comment.user.avatar.url, height: '64', width: '64') %>
                     <%end%>
                     </div><!-- /thumbnail -->
                     </div><!-- /col-sm-1 -->

                     <div class="col-sm-5">
                     <div class="panel panel-default">
                     <div class="panel-heading">
                     <strong><%=comment.user.name%></strong> <span class="text-muted"><%=comment.created_at%></span>
                     </div>
                     <div class="panel-body">
                     <%= comment.comment %> <br>
                     </div><!-- /panel-body -->
                     </div><!-- /panel panel-default -->
                     </div><!-- /col-sm-5 -->
                     </div><!-- /row -->


                   <% end %>
                </div>
                <div class="comment box">

                  <div class="container">
                    <div class="row">
                      <h3>Add Comment</h3>
                    </div>

                    <div class="row">
                      <div class="col-md-6">
                           <div class="widget-area no-padding blank">
                           <div class="status-upload">
                             <%= form_tag create_comment_path, method: "post" do %>
                             <%= hidden_field_tag "id", post.id %>
                             <%= text_area_tag :comment %>
                             <button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> comment</button>
                             <% end %>
                           </div><!-- Status Upload  -->
                         </div><!-- Widget Area -->
                       </div>
                     </div>
                   </div>
                </div>

              <%end%>
              </div>

            </div>
		</div>
	</div>
</div>
<br>
<br>